### ISSUE TITLE
CircuitPython support is ready for XIAO ESP32S3

### ISSUE THREAD

**Issue by marcobrianza** [Seeed-Studio/OSHW-XIAO-Series#21]
Hello,
CircuitPython support is ready and just need seeedstudio to provide the specific VID / PID for this board

https://github.com/adafruit/circuitpython/issues/9507

**Comment by ackPeng** [comment]
Thank you very much, we will discuss this matter

**Comment by Pillar1989** [comment]
@marcobrianza  Thank you so much for your support. Thank you again.
